dist: osx

language: python
node_js:
  - "7"
python:
   - "3.6"
   
# command to run tests
script:
 - python tests/tests.py

addons:
  postgresql: "9.6"
  chrome: stable

env:
  RDS_test_USERNAME=postgres
  RDS_test_PASSWORD=""
  RDS_test_DB_NAME=fscafold
  RDS_test_HOSTNAME="localhost"

before_script:
  - psql -c 'create database fscafold;' -U postgres
  - npm install --prefix ./app/templates/static/
  - python scaffold.py scaffold/blog.yaml
  - python db.py db init
  - python db.py db migrate
  - python db.py db upgrade
  - python run.py &
  - sleep 3
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - sleep 3