sudo: required
dist: trusty

language: python
python:
   - "3.4"

# command to run tests
script: 
 - protractor /home/travis/build/Leo-G/Flask-Scaffold/pro-tests/conf.js
 - bash tests.bash
 
addons:
  postgresql: "9.3"

before_script:
  - sudo apt-get update -q
  - sudo apt-get install -y nginx
  - sudo cp /home/travis/build/Leo-G/Flask-Scaffold/nginx/localhost.conf /etc/nginx/sites-enabled/
  - sudo cp -f nginx/nginx.conf /etc/nginx/nginx.conf
  - sudo rm -rf /etc/nginx/sites-enabled/default
  - sudo ls -l /etc/nginx/sites-enabled/ 
  - sudo cp -R /home/travis/build/Leo-G/Flask-Scaffold /tmp
  - sudo chown -R www-data:www-data /tmp/Flask-Scaffold/
  - sudo ls -l /tmp/Flask-Scaffold/
  - sudo service nginx restart
  - sleep 3
  #For testing purposes only
  #- sudo apt-get install curl
  #- curl localhost:8080
  - sudo wget -qO- https://deb.nodesource.com/setup_4.x | sudo bash -
  - sudo apt-get install -y nodejs
  - nodejs -v
  - sudo npm install -g protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - psql -c 'create database fscafold;' -U postgres
  - python scaffold.py scaffold/module.yaml
  - python db.py db init
  - python db.py db migrate
  - python db.py db upgrade
  - sudo webdriver-manager update
  - sudo webdriver-manager start --standalone &
  #give time for server to start
  - sleep 4
  - uwsgi --socket 127.0.0.1:8001  --wsgi-file /home/travis/build/Leo-G/Flask-Scaffold/run.py --callable app --processes 4 --threads 2 &

