branch-defaults:
  dev:
    environment: flask-ang2-env
    group_suffix: null
  master:
    environment: null
    group_suffix: null
environment-defaults:
  flask-3-6:
    branch: master
    repository: codecommit-origin
global:
  application_name: nims-final
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
