"""empty message

Revision ID: 062496932bc3
Revises: ef3fab1c6d91
Create Date: 2018-11-03 18:45:50.636728

"""

# revision identifiers, used by Alembic.
revision = '062496932bc3'
down_revision = 'ef3fab1c6d91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
