"""empty message

Revision ID: 724b72bb0902
Revises: bedb2d6be9a1
Create Date: 2018-11-03 18:34:02.754648

"""

# revision identifiers, used by Alembic.
revision = '724b72bb0902'
down_revision = 'bedb2d6be9a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('createddate', sa.Date(), nullable=False),
    sa.Column('createdby', sa.String(length=250), nullable=False),
    sa.Column('updateddate', sa.Date(), nullable=False),
    sa.Column('updatedby', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
