"""empty message

Revision ID: 7694f433d36c
Revises: 65f25e38f0be
Create Date: 2018-11-03 18:53:28.047724

"""

# revision identifiers, used by Alembic.
revision = '7694f433d36c'
down_revision = '65f25e38f0be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updateddate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updateddate')
    # ### end Alembic commands ###
