"""empty message

Revision ID: a13de1ec67d5
Revises: None
Create Date: 2018-11-03 18:18:18.714694

"""

# revision identifiers, used by Alembic.
revision = 'a13de1ec67d5'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('alarms')
    op.drop_table('modules')
    op.drop_index('ix_deviceid', table_name='profiledevices')
    op.drop_index('ix_profileid', table_name='profiledevices')
    op.drop_table('profiledevices')
    op.drop_table('railways')
    op.drop_table('districts')
    op.drop_table('profilemodules')
    op.drop_table('devicerailwaymapping')
    op.drop_table('states')
    op.drop_table('devices')
    op.drop_table('railwaystatemapping')
    op.drop_table('voltagehistory')
    op.add_column('users', sa.Column('name', sa.String(length=250), nullable=False))
    op.alter_column('users', 'updatedby',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'updateddate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('fk_dbo.users_dbo.profiles_profileid', 'users', type_='foreignkey')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'status')
    op.drop_column('users', 'saltvalue')
    op.drop_column('users', 'username')
    op.drop_column('users', 'address')
    op.drop_column('users', 'profileid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('saltvalue', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_dbo.users_dbo.profiles_profileid', 'users', 'profiles', ['profileid'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'updateddate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updatedby',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'name')
    op.create_table('voltagehistory',
    sa.Column('deviceid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('createddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('voltage', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deviceid'], ['devices.id'], name='fk_dbo.voltagehistory_dbo.devices_deviceid', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deviceid', 'createddate', name='pk_dbo.voltagehistory')
    )
    op.create_table('railwaystatemapping',
    sa.Column('railwayid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stateid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('createddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createdby', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updateddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedby', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['railwayid'], ['railways.id'], name='fk_dbo.railwaystatemapping_dbo.railways_railwayid', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stateid'], ['states.id'], name='fk_dbo.railwaystatemapping_dbo.states_stateid', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('railwayid', 'stateid', name='pk_dbo.railwaystatemapping')
    )
    op.create_table('devices',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nodeid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('voltage', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('selftest', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batterylevel', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('createddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createdby', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updateddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedby', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('districtid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['districtid'], ['districts.id'], name='fk_dbo.devices_dbo.districts_districtid'),
    sa.PrimaryKeyConstraint('id', name='pk_dbo.devices'),
    postgresql_ignore_search_path=False
    )
    op.create_table('states',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_dbo.states')
    )
    op.create_table('devicerailwaymapping',
    sa.Column('deviceid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('railwayid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('createddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createdby', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updateddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedby', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deviceid'], ['devices.id'], name='fk_dbo.devicerailwaymapping_dbo.devices_deviceid', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['railwayid'], ['railways.id'], name='fk_dbo.devicerailwaymapping_dbo.railways_railwayid', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deviceid', 'railwayid', 'createddate', 'createdby', 'updateddate', 'updatedby', name='pk_dbo.devicerailwaymapping')
    )
    op.create_table('profilemodules',
    sa.Column('profileid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('editaction', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('profileid', 'moduleid', name='pk_dbo.profilemodules')
    )
    op.create_table('districts',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_dbo.districts'),
    postgresql_ignore_search_path=False
    )
    op.create_table('railways',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('createdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createby', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updatedate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updateby', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_dbo.railways')
    )
    op.create_table('profiledevices',
    sa.Column('profileid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('deviceid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('profileid', 'deviceid', name='pk_dbo.profiledevices')
    )
    op.create_index('ix_profileid', 'profiledevices', ['profileid'], unique=False)
    op.create_index('ix_deviceid', 'profiledevices', ['deviceid'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('modulename', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('editflag', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tabindex', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_dbo.modules')
    )
    op.create_table('alarms',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('deviceid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('batterylevellessthan', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('fromvoltage', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('tovoltage', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('createdby', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('updatedby', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deviceid'], ['devices.id'], name='fk_dbo.alarms_dbo.devices_deviceid', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_dbo.alarms')
    )
    op.create_table('profiles',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_dbo.profiles')
    )
    # ### end Alembic commands ###
