"""empty message

Revision ID: dbc42c2cc690
Revises: 062496932bc3
Create Date: 2018-11-03 18:46:25.216368

"""

# revision identifiers, used by Alembic.
revision = 'dbc42c2cc690'
down_revision = '062496932bc3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'createddate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createddate', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
