"""empty message

Revision ID: ef3fab1c6d91
Revises: 724b72bb0902
Create Date: 2018-11-03 18:38:53.580253

"""

# revision identifiers, used by Alembic.
revision = 'ef3fab1c6d91'
down_revision = '724b72bb0902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
